repos:
  - repo: local
    hooks:
      - id: compile23
        name: Compile python files using the expected runtime version
        entry: ./tools/compile23.py
        language: script
      - id: bad-import-000
        name: Incompatible import with old versions in tests and `0.0.0` scripts
        language: pygrep
        entry: '(from|import) odoo.upgrade\b'
        files: '^src/\w+/(tests|0\.0\.0)/.*\.py$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
    - id: ruff
      name: Check code with Ruff, apply automatic fixes
      args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        name: Format code with Black automatically
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-symlinks
    - id: debug-statements
